### ISSUE TITLE
[Bug]: Performance problem on the server/devtool.

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/lenra_cli#340]
### What happened?

It seems that when running a lot of requests to the server api on a lenra application, in my case a couple thousand requests, the server starts rebuilding the UI at each request and it also seems that either it reloads the UI MUCH more than at each request but more like 100 times per request or either the logging system is duplicating the logs. 

In fact, my log file is 1.5 million lines long for the mere couple thousand requests, it seems quite high for that.

**Comment by taorepoara** [comment]
@jonas-martinez Is this resolved by the insertMany ?

**Comment by jonas-martinez** [comment]
@taorepoara This problem is still here even with the insertMany and pagination system. 

I don't know why but when I run my requests for getting my steam games and achievements, even though my UI is not supposed to be reloaded, the server tries to do it (and does not send the result on the websocket). So I think that there is a problem somewhere in the UI rebuild system that triggers everytime any entry in the Mongo database is updated/created.

You can see this behaviour in the log file attached to the description of this issue.
